# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - package_api_docs
    - unnecessary_await_in_return
