name: did_you_mean
description: a dart port of didyoumean, but use faster levenshtein algorithm.
version: 1.0.1
homepage: https://github.com/cbbfcd/did_you_mean

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
