name: dart_lib_starter
description: Super simple dart lib starter to keep me happy.
version: 0.0.1
homepage: https://github.com/cbbfcd/dart-lib-starter

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0