name: did_you_mean
description: a dart port of didyoumean.
version: 1.0.0
homepage: https://github.com/cbbfcd/did_you_mean

environment:
  sdk: '>=2.17.0 <3.2.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
